name: Deploy website

on: [repository_dispatch]

jobs:
  deploy-website:

    env: 
      INPUT_USER_NAME: ${{ github.event.client_payload.user_name }}
      INPUT_USER_EMAIL: ${{ github.event.client_payload.user_email }}
      INPUT_SRC_BRANCH: ${{ github.event.client_payload.src_branch }}
      INPUT_DST_BRANCH: ${{ github.event.client_payload.dst_branch }}
      INPUT_COMMIT_MSG: ${{ github.event.client_payload.commit_msg }}
      INPUT_TAG: ${{ github.event.client_payload.tag }}
      INPUT_TAG_MSG: ${{ github.event.client_payload.tag_msg }}
      SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SECRET_FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      SECRET_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      SECRET_FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.client_payload.src_branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Deploy website
        if: success()
        run: |
          git config --local user.email "${INPUT_USER_EMAIL}"
          git config --local user.name "${INPUT_USER_NAME}"
          git checkout -b "${INPUT_DST_BRANCH}"
          yarn install
          yarn global add firebase-tools@latest
          node scripts/exportDB "${SECRET_FIREBASE_SERVICE_ACCOUNT}" "${SECRET_FIREBASE_DATABASE_URL}"
          git add db
          git diff-index --quiet HEAD || git commit -m "${INPUT_COMMIT_MSG}"
          git tag -a "${INPUT_TAG}" -m "${INPUT_TAG_MSG}"
          git push "https://${INPUT_USER_NAME}:${SECRET_GITHUB_TOKEN}@github.com/gatsby-github-actions.git" HEAD:${INPUT_DST_BRANCH} --follow-tags
          yarn build
          firebase deploy --token "${SECRET_FIREBASE_TOKEN}" --only hosting --non-interactive