name: publish
on: [repository_dispatch, publish]
jobs:
  publish:
    name: install, build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
    - run: yarn publish